### ISSUE TITLE
Build with Kernel 6.11 Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by tea0112** [ty2/ideapad-laptop-tb2024g6plus#9]
I've just install Ubuntu 24.04.1 LTS but the make show error like this
```
make -C /lib/modules/6.11.0-17-generic/build/ M=/home/vmo/workspace/ideapad-laptop-tb2024g6plus modules
make[1]: Entering directory '/usr/src/linux-headers-6.11.0-17-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /home/vmo/workspace/ideapad-laptop-tb2024g6plus/ideapad-laptop-tb2024g6plus.o
/home/vmo/workspace/ideapad-laptop-tb2024g6plus/ideapad-laptop-tb2024g6plus.c:35:10: fatal error: ideapad-laptop.h: No such file or directory
   35 | #include "ideapad-laptop.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [scripts/Makefile.build:244: /home/vmo/workspace/ideapad-laptop-tb2024g6plus/ideapad-laptop-tb2024g6plus.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.11.0-17-generic/Makefile:1931: /home/vmo/workspace/ideapad-laptop-tb2024g6plus] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.11.0-17-generic'
make: *** [Makefile:14: all] Error 2

```

**Comment by Byntonna** [comment]
Same issue

**Comment by berrylium0078** [comment]
Same issue on 6.13.5-arch1-1, changing it to ideapad-laptop-tb2024g6plus.h worked for me.

**Comment by berrylium0078** [comment]
It appears that the patch isn't working.

**Comment by berrylium0078** [comment]
This worked for me:
```sh
mv ideapad-laptop-tb2024g6plus.c ideapad-laptop.c
patch < ideapad-laptop.patch
mv ideapad-laptop.c ideapad-laptop-tb2024g6plus.c
make
```

**Comment by berrylium0078** [comment]
p.s. @ty2 please update AUR package.

**Comment by ferstar** [comment]
@berrylium0078 @Byntonna  try my fork: https://github.com/ferstar/ideapad-laptop-tb 😄
